export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const OTP_VERIFICATION_EMAIL_REQUEST = 'OTP_VERIFICATION_EMAIL_REQUEST';
export const OTP_VERIFICATION_EMAIL_SUCCESS = 'OTP_VERIFICATION_EMAIL_SUCCESS';
export const OTP_VERIFICATION_EMAIL_FAIL = 'OTP_VERIFICATION_EMAIL_FAIL';


export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';


export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';


export const VERIFY_OTP_CODE_REQUEST = 'VERIFY_OTP_CODE_REQUEST';
export const VERIFY_OTP_CODE_SUCCESS = 'VERIFY_OTP_CODE_SUCCESS';
export const VERIFY_OTP_CODE_FAIL = 'VERIFY_OTP_CODE_FAIL';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
