
export const ADD_ITEM_TO_CART_REQUEST = 'ADD_ITEM_TO_CART_REQUEST';
export const ADD_ITEM_TO_CART_SUCCESS = 'ADD_ITEM_TO_CART_SUCCESS';
export const ADD_ITEM_TO_CART_FAIL = 'ADD_ITEM_TO_CART_FAIL';


export const GET_CART_REQUEST = 'GET_CART_REQUEST';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAIL = 'GET_CART_FAIL';


export const VERIFY_PROMO_CODE_REQUEST = 'VERIFY_PROMO_CODE_REQUEST';
export const VERIFY_PROMO_CODE_SUCCESS = 'VERIFY_PROMO_CODE_SUCCESS';
export const VERIFY_PROMO_CODE_FAIL = 'VERIFY_PROMO_CODE_FAIL';


export const FINALIZE_ORDER_REQUEST = 'FINALIZE_ORDER_REQUEST';
export const FINALIZE_ORDER_SUCCESS = 'FINALIZE_ORDER_SUCCESS';
export const FINALIZE_ORDER_FAIL = 'FINALIZE_ORDER_FAIL';


export const GET_GENERAL_SETTINGS_REQUEST = 'GET_GENERAL_SETTINGS_REQUEST';
export const GET_GENERAL_SETTINGS_SUCCESS = 'GET_GENERAL_SETTINGS_SUCCESS';
export const GET_GENERAL_SETTINGS_FAIL = 'GET_GENERAL_SETTINGS_FAIL';
