export const GET_UPCOMING_ORDERS_REQUEST = 'GET_UPCOMING_ORDERS_REQUEST';
export const GET_UPCOMING_ORDERS_SUCCESS = 'GET_UPCOMING_ORDERS_SUCCESS';
export const GET_UPCOMING_ORDERS_FAIL = 'GET_UPCOMING_ORDERS_FAIL';

export const GET_PAST_ORDERS_REQUEST = 'GET_PAST_ORDERS_REQUEST';
export const GET_PAST_ORDERS_SUCCESS = 'GET_PAST_ORDERS_SUCCESS';
export const GET_PAST_ORDERS_FAIL = 'GET_PAST_ORDERS_FAIL';


export const GET_ORDER_BY_ORDER_ID_REQUEST = 'GET_ORDER_BY_ORDER_ID_REQUEST';
export const GET_ORDER_BY_ORDER_ID_SUCCESS = 'GET_ORDER_BY_ORDER_ID_SUCCESS';
export const GET_ORDER_BY_ORDER_ID_FAIL = 'GET_ORDER_BY_ORDER_ID_FAIL';


export const ADD_ORDER_REVIEW_REQUEST = 'ADD_ORDER_REVIEW_REQUEST';
export const ADD_ORDER_REVIEW_SUCCESS = 'ADD_ORDER_REVIEW_SUCCESS';
export const ADD_ORDER_REVIEW_FAIL = 'ADD_ORDER_REVIEW_FAIL';


export const DELETE_ORDER_REVIEW_REQUEST = 'DELETE_ORDER_REVIEW_REQUEST';
export const DELETE_ORDER_REVIEW_SUCCESS = 'DELETE_ORDER_REVIEW_SUCCESS';
export const DELETE_ORDER_REVIEW_FAIL = 'DELETE_ORDER_REVIEW_FAIL';



export const CANCEL_ORDER_REQUEST = 'CANCEL_ORDER_REQUEST';
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';
export const CANCEL_ORDER_FAIL = 'CANCEL_ORDER_FAIL';
