export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

export const GET_USER_REVIEWS_REQUEST = 'GET_USER_REVIEWS_REQUEST';
export const GET_USER_REVIEWS_SUCCESS = 'GET_USER_REVIEWS_SUCCESS';
export const GET_USER_REVIEWS_FAIL = 'GET_USER_REVIEWS_FAIL';

export const UPDATE_CUSTOMER_PIC_REQUEST = 'UPDATE_CUSTOMER_PIC_REQUEST';
export const UPDATE_CUSTOMER_PIC_SUCCESS = 'UPDATE_CUSTOMER_PIC_SUCCESS';
export const UPDATE_CUSTOMER_PIC_FAIL = 'UPDATE_CUSTOMER_PIC_FAIL';

export const UPDATE_CUSTOMER_REQUEST = 'UPDATE_CUSTOMER_REQUEST';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER_FAIL = 'UPDATE_CUSTOMER_FAIL';


export const DELETE_USER_ACCOUNT_REQUEST = 'DELETE_USER_ACCOUNT_REQUEST';
export const DELETE_USER_ACCOUNT_SUCCESS = 'DELETE_USER_ACCOUNT_SUCCESS';
export const DELETE_USER_ACCOUNT_FAIL = 'DELETE_USER_ACCOUNT_FAIL';

export const SAVE_DEVICE_TOKEN_REQUEST = "SAVE_DEVICE_TOKEN_REQUEST";
export const SAVE_DEVICE_TOKEN_SUCCESS = "SAVE_DEVICE_TOKEN_SUCCESS";
export const SAVE_DEVICE_TOKEN_FAILED = "SAVE_DEVICE_TOKEN_FAILED";




export const GET_CURRENCY_LIST_REQUEST = "GET_CURRENCY_LIST_REQUEST";
export const GET_CURRENCY_LIST_SUCCESS = "GET_CURRENCY_LIST_SUCCESS";
export const GET_CURRENCY_LIST_FAILED = "GET_CURRENCY_LIST_FAILED";

