export const GET_POPULAR_RESTAUARANTS_REQUEST = 'GET_POPULAR_RESTAUARANTS_REQUEST';
export const GET_POPULAR_RESTAUARANTS_SUCCESS = 'GET_POPULAR_RESTAUARANTS_SUCCESS';
export const GET_POPULAR_RESTAUARANTS_FAIL = 'GET_POPULAR_RESTAUARANTS_FAIL';

export const GET_DISCOUNTED_RESTAUARANTS_REQUEST = 'GET_DISCOUNTED_RESTAUARANTS_REQUEST';
export const GET_DISCOUNTED_RESTAUARANTS_SUCCESS = 'GET_DISCOUNTED_RESTAUARANTS_SUCCESS';
export const GET_DISCOUNTED_RESTAUARANTS_FAIL = 'GET_DISCOUNTED_RESTAUARANTS_FAIL';


export const GET_ALL_RESTAUARANTS_REQUEST = 'GET_ALL_RESTAUARANTS_REQUEST';
export const GET_ALL_RESTAUARANTS_SUCCESS = 'GET_ALL_RESTAUARANTS_SUCCESS';
export const GET_ALL_RESTAUARANTS_FAIL = 'GET_ALL_RESTAUARANTS_FAIL';


export const GET_ALL_ITEMS_REQUEST = 'GET_ALL_ITEMS_REQUEST';
export const GET_ALL_ITEMS_SUCCESS = 'GET_ALL_ITEMS_SUCCESS';
export const GET_ALL_ITEMS_FAIL = 'GET_ALL_ITEMS_FAIL';


export const GET_FAVOURITES_REQUEST = 'GET_FAVOURITES_REQUEST';
export const GET_FAVOURITES_SUCCESS = 'GET_FAVOURITES_SUCCESS';
export const GET_FAVOURITES_FAIL = 'GET_FAVOURITES_FAIL';


export const DELETE_FAVOURITES_REQUEST = 'DELETE_FAVOURITES_REQUEST';
export const DELETE_FAVOURITES_SUCCESS = 'DELETE_FAVOURITES_SUCCESS';
export const DELETE_FAVOURITES_FAIL = 'DELETE_FAVOURITES_FAIL';


export const ADD_FAVOURITES_REQUEST = 'ADD_FAVOURITES_REQUEST';
export const ADD_FAVOURITES_SUCCESS = 'ADD_FAVOURITES_SUCCESS';
export const ADD_FAVOURITES_FAIL = 'ADD_FAVOURITES_FAIL';


export const GET_RESTAURANT_BY_ID_REQUEST = 'GET_RESTAURANT_BY_ID_REQUEST';
export const GET_RESTAURANT_BY_ID_SUCCESS = 'GET_RESTAURANT_BY_ID_SUCCESS';
export const GET_RESTAURANT_BY_ID_FAIL = 'GET_RESTAURANT_BY_ID_FAIL';



export const GET_ITEMS_BY_ID_REQUEST = 'GET_ITEMS_BY_ID_REQUEST';
export const GET_ITEMS_BY_ID_SUCCESS = 'GET_ITEMS_BY_ID_SUCCESS';
export const GET_ITEMS_BY_ID_FAIL = 'GET_ITEMS_BY_ID_FAIL';


export const GET_RESTAURANT_REVIEWS_REQUEST = 'GET_RESTAURANT_REVIEWS_REQUEST';
export const GET_RESTAURANT_REVIEWS_SUCCESS = 'GET_RESTAURANT_REVIEWS_SUCCESS';
export const GET_RESTAURANT_REVIEWS_FAIL = 'GET_RESTAURANT_REVIEWS_FAIL';


export const FILTER_BY_CATEGORY_REQUEST = 'FILTER_BY_CATEGORY_REQUEST';
export const FILTER_BY_CATEGORY_SUCCESS = 'FILTER_BY_CATEGORY_SUCCESS';
export const FILTER_BY_CATEGORY_FAIL = 'FILTER_BY_CATEGORY_FAIL';