const IMAGES = {
  splash_icon: require('../assets/images/splash_icon.png'),
  onboarding1: require('../assets/images/onboarding1.png'),
  onboarding2: require('../assets/images/onboarding2.png'),
  onboarding3: require('../assets/images/onboarding3.png'),
  google: require('../assets/images/google.png'),
  motocycle: require('../assets/images/motocycle.png'),
  alarm: require('../assets/images/alarm.png'),
  burger: require('../assets/images/burger.png'),
  user: require('../assets/images/user.png'),
  purse: require('../assets/images/purse.png'),
  bell: require('../assets/images/bell.png'),

  mark: require('../assets/images/mark.png'),
  info: require('../assets/images/info.png'),
  location: require('../assets/images/location.png'),
  bill: require('../assets/images/bill.png'),
  favorite: require('../assets/images/favorite.png'),
  logout: require('../assets/images/logout.png'),
  camera: require('../assets/images/camera.png'),
  locationHand: require('../assets/images/location-hand.png'),
  hand: require('../assets/images/hand.png'),
  default: require('../assets/images/default.png'),
  defaultImage: require('../assets/images/defaultImage.png'),
  heart: require('../assets/images/heart.png'),
  no_orders: require('../assets/images/no_orders.png'),
  no_addresses: require('../assets/images/no_addresses.png'),
  no_payments: require('../assets/images/no_payments.png'),
  no_notification: require('../assets/images/no_notification.png'),
  no_favourites: require('../assets/images/no_favourites.png'),
  no_reviews: require('../assets/images/no_reviews.png'),
  currency: require('../assets/images/currency.png'),
  animated_app_splash_screen: require('../assets/images/animated_app_splash_screen.json'),
  no_conexion: require('../assets/images/no_conexion.png'),
  logo: require('../assets/images/logo.png'),
  pin: require('../assets/images/pin.png'),
  mail: require('../assets/images/mail.png'),
  whatsapp: require('../assets/images/whatsapp.png'),
  current_location: require('../assets/images/current_location.png')

}

export default IMAGES;
